# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(237, 361)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 236, 61))
        self.label.setStyleSheet("QLabel{\n"
"\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 24pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255)\n"
"    \n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButton_silme = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_silme.setGeometry(QtCore.QRect(0, 60, 61, 61))
        self.pushButton_silme.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_silme.setObjectName("pushButton_silme")
        self.pushButton_isaret = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_isaret.setGeometry(QtCore.QRect(59, 60, 61, 61))
        self.pushButton_isaret.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_isaret.setObjectName("pushButton_isaret")
        self.pushButton_bolme = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bolme.setGeometry(QtCore.QRect(117, 60, 61, 61))
        self.pushButton_bolme.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_bolme.setObjectName("pushButton_bolme")
        self.pushButton_carpma = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_carpma.setGeometry(QtCore.QRect(175, 60, 61, 61))
        self.pushButton_carpma.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_carpma.setObjectName("pushButton_carpma")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 120, 61, 61))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(117, 120, 61, 61))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(59, 120, 61, 61))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_cikarma = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cikarma.setGeometry(QtCore.QRect(175, 120, 61, 61))
        self.pushButton_cikarma.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_cikarma.setObjectName("pushButton_cikarma")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 180, 61, 61))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 240, 61, 61))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 240, 57, 61))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(117, 180, 61, 61))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(59, 180, 61, 61))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_toplama = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_toplama.setGeometry(QtCore.QRect(175, 180, 61, 61))
        self.pushButton_toplama.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}")
        self.pushButton_toplama.setObjectName("pushButton_toplama")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 240, 61, 61))
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_nokta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nokta.setGeometry(QtCore.QRect(117, 300, 60, 61))
        self.pushButton_nokta.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_nokta.setObjectName("pushButton_nokta")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 300, 121, 61))
        self.pushButton_0.setStyleSheet("QPushButton{\n"
"background-color: rgb(128, 128, 128);\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_esit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_esit.setGeometry(QtCore.QRect(176, 240, 61, 121))
        self.pushButton_esit.setStyleSheet("QPushButton{\n"
"font: italic 9pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(218, 165, 32);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:selected{\n"
"background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 224);\n"
"}\n"
"\n"
"")
        self.pushButton_esit.setObjectName("pushButton_esit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton_silme.setText(_translate("MainWindow", "C"))
        self.pushButton_isaret.setText(_translate("MainWindow", "+-"))
        self.pushButton_bolme.setText(_translate("MainWindow", "/"))
        self.pushButton_carpma.setText(_translate("MainWindow", "X"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_cikarma.setText(_translate("MainWindow", "-"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_toplama.setText(_translate("MainWindow", "+"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_nokta.setText(_translate("MainWindow", "."))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_esit.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
