# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mail.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(618, 620)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Email-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("alternate-background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 161, 21))
        self.label.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.lineEdit_gonderici = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gonderici.setGeometry(QtCore.QRect(180, 110, 171, 21))
        self.lineEdit_gonderici.setStyleSheet("font: 75 9pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_gonderici.setObjectName("lineEdit_gonderici")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 131, 21))
        self.label_2.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_gonderici.setPlaceholderText("a_saroglu@gmail.com")
        self.lineEdit_gonderici_sifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gonderici_sifre.setGeometry(QtCore.QRect(180, 150, 171, 21))
        self.lineEdit_gonderici_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_gonderici_sifre.setObjectName("lineEdit_gonderici_sifre")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 161, 21))
        self.label_3.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_alan_adres = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_alan_adres.setGeometry(QtCore.QRect(180, 190, 171, 21))
        self.lineEdit_alan_adres.setStyleSheet("font: 75 9pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_alan_adres.setObjectName("lineEdit_alan_adres")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 270, 91, 16))
        self.label_4.setStyleSheet("font: 15pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 500, 211, 61))
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"QPushButton:pressed{\n"
"selection-color: rgb(183, 255, 253);\n"
"    \n"
"    background-color: rgb(213, 255, 254);\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Send-message-2-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 20, 391, 61))
        self.label_5.setStyleSheet("font: 22pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 161, 21))
        self.label_6.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit_mail_konu = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mail_konu.setGeometry(QtCore.QRect(180, 230, 171, 21))
        self.lineEdit_mail_konu.setStyleSheet("font: 75 9pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_mail_konu.setObjectName("lineEdit_mail_konu")
        self.lineEdit_Konu = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Konu.setGeometry(QtCore.QRect(10, 300, 501, 171))
        self.lineEdit_Konu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Konu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_Konu.setObjectName("lineEdit_Konu")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "E-Posta Adresinizi Giriniz :"))
        self.label_2.setText(_translate("MainWindow", "    Şifrenizi Giriniz :"))
        self.lineEdit_gonderici_sifre.setStyleSheet(_translate("MainWindow", "font: 75 9pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);"))
        self.label_3.setText(_translate("MainWindow", "Gönderici Adresi Giriniz :"))
        self.label_4.setText(_translate("MainWindow", "Mesajınız"))
        self.pushButton.setText(_translate("MainWindow", "GÖNDER"))
        self.label_5.setText(_translate("MainWindow", "E-POSTA GÖNDERME"))
        self.label_6.setText(_translate("MainWindow", "Mail Konusu Giriniz :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
