# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 433)
        MainWindow.setStyleSheet("")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 170, 461, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.link=self.lineEdit
        self.link.setPlaceholderText("https://www.youtube.com/watch?v=kJQP7kiw5Fk")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 250, 231, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(170, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"QPushButton:pressed{\n"
"selection-color: rgb(183, 255, 253);\n"
"    \n"
"    background-color: rgb(213, 255, 254);\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 40, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 685, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuDaha_Fazla = QtWidgets.QMenu(self.menuBar)
        self.menuDaha_Fazla.setObjectName("menuDaha_Fazla")
        MainWindow.setMenuBar(self.menuBar)
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.actionHakk_mda = QtWidgets.QAction(MainWindow)
        self.actionHakk_mda.setObjectName("actionHakk_mda")
        self.actionHakk_mda_2 = QtWidgets.QAction(MainWindow)
        self.actionHakk_mda_2.setObjectName("actionHakk_mda_2")
        self.menuDaha_Fazla.addAction(self.actionHakk_mda_2)
        self.menuBar.addAction(self.menuDaha_Fazla.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "YOUTUBE URL :"))
        self.pushButton.setText(_translate("MainWindow", "İNDİR"))
        self.label_2.setText(_translate("MainWindow", "     YOUTUBE İNDİRİCİ"))
        self.menuDaha_Fazla.setTitle(_translate("MainWindow", "Daha Fazla.."))
        self.actionA.setText(_translate("MainWindow", "Aç"))
        self.actionHakk_mda.setText(_translate("MainWindow", "Hakkımda"))
        self.actionHakk_mda_2.setText(_translate("MainWindow", "Hakkımda"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
